# Generated by Django 4.2.20 on 2025-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
